ansible_connection: winrm
ansible_user: "ansible"
ansible_password: "StrongPassword123!"
ansible_winrm_transport: ntlm
ansible_winrm_server_cert_validation: ignore

target_admin_password: "StrongPassword123!"
