---
- name: Download the installation script
  get_url:
    url: "http://{{ fleet-server }}/{{ file }}"
    dest: "/tmp/{{ file }}"
  become: true

- name: Execute the installation script on Linux
  shell: |
    bash /tmp/{{ file }}
  args:
    executable: /bin/bash
  become: true
