---
- name: Update APT package index
  apt:
    update_cache: yes
  become: true

- name: Install ca-certificates and curl
  apt:
    name:
      - ca-certificates
      - curl
    state: present
  become: true

- name: Create directory for apt keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  become: true

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  become: true

- name: Add Docker repository to Apt sources
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  become: true

- name: Update APT package index again
  apt:
    update_cache: yes
  become: true

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true

- name: Clone the docker-elk repository
  git:
    repo: https://github.com/deviantony/docker-elk.git
    dest: /opt/docker-elk
  become: true


- name: Start Docker Compose services
  command: docker compose up setup
  args:
    chdir: /opt/docker-elk
  become: true

- name: Display Docker Compose services status
  command: docker compose -f docker-compose.yml -f extensions/fleet/fleet-compose.yml up -d
  args:
    chdir: /opt/docker-elk
  become: true

- name: Ensure Python is installed
  ansible.builtin.yum:
    name: python3
    state: present
  become: true

- name: Run the Python script to create agent policies and package policies
  ansible.builtin.command:
    cmd: python3 files/createPolicy.py --path files/windows
  environment:
    KIBANA_USERNAME: "elastic"
    KIBANA_PASSWORD: "changeme"
    KIBANA_URL: "http://localhost:5601"
  register: python_script_output

- name: Print output of Python script
  ansible.builtin.debug:
    var: python_script_output.stdout