---
- name: Update APT package index
  apt:
    update_cache: yes
  become: true

- name: Install ca-certificates and curl
  apt:
    name:
      - ca-certificates
      - curl
    state: present
  become: true

- name: Create directory for apt keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  become: true

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  become: true

- name: Add Docker repository to Apt sources
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  become: true

- name: Update APT package index again
  apt:
    update_cache: yes
  become: true

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true

- name: Clone the docker-elk repository
  git:
    repo: https://github.com/deviantony/docker-elk.git
    dest: /opt/docker-elk
    force: true
  become: true

- name: Copy agent.sh template to /tmp/AgentInstallerScripts
  template:
    src: templates/kibana.yml.j2
    dest: /opt/docker-elk/kibana/config/kibana.yml
    mode: "0755"
  become: true

- name: Start Docker Compose services
  command: docker compose up setup
  args:
    chdir: /opt/docker-elk
  become: true

- name: Display Docker Compose services status
  command: docker compose -f docker-compose.yml -f extensions/fleet/fleet-compose.yml up -d
  args:
    chdir: /opt/docker-elk
  become: true

- name: Copy 'file' directory recursively to the target machine
  ansible.builtin.copy:
    src: AgentPolicies
    dest: "/tmp/"
    mode: "0755"
    remote_src: no

- name: Ensure Python 3 is installed on the target machine
  ansible.builtin.apt:
    name: python3
    state: present
  become: true

- name: Ensure /tmp/AgentInstallerScripts directory exists
  file:
    path: /tmp/AgentInstallerScripts
    state: directory
    mode: "0755"

- name: Copy agent.sh template to /tmp/AgentInstallerScripts
  template:
    src: templates/linux_agent_install.sh.j2
    dest: /tmp/AgentInstallerScripts/linux_agent_install.sh
    mode: "0755"

- name: Copy agent.ps1 template to /tmp/AgentInstallerScripts
  template:
    src: templates/windows_agent_install.ps1.j2
    dest: /tmp/AgentInstallerScripts/windows_agent_install.ps1
    mode: "0755"

- name: Wait until kibana status is 200
  uri:
    url: "http://localhost:5601/"
    return_content: yes
    validate_certs: no
    status_code:
      - 200
  register: kibana_status
  retries: 30 # Number of attempts
  delay: 10 # Wait 10 seconds between attempts
  until: kibana_status.status == 200 or 'Kibana server is not ready yet' not in (kibana_status.content | default(''))
  ignore_errors: true # Continue even if the check fails initially

- name: Download Elastic Agent for linux
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.15.4-linux-x86_64.tar.gz
    dest: /var/www/html/elastic-agent-8.15.4-linux-x86_64.tar.gz
    mode: "0644"
  become: true

- name: Download Elastic Agent for windows
  get_url:
    url: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.15.4-windows-x86_64.zip
    dest: /var/www/html/elastic-agent-8.15.4-windows-x86_64.zip
    mode: "0644"
  become: true

- name: Run the Python script for proxy
  ansible.builtin.command:
    cmd: python3 /tmp/AgentPolicies/createPolicy.py --path /tmp/AgentPolicies/windows --os=windows --url="http://localhost:5601" --username="elastic" --password="changeme"
  become: true

- name: Run the Python script for proxy
  ansible.builtin.command:
    cmd: python3 /tmp/AgentPolicies/createPolicy.py --path /tmp/AgentPolicies/proxy --os=linux --url="http://localhost:5601" --username="elastic" --password="changeme"
  become: true
