- name: Update apt packages
  become: true
  apt:
    upgrade: yes

- name: Update the system
  apt:
    update_cache: yes
  become: true

- name: Install openvpn
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openvpn
    - easy-rsa
    - libpam-google-authenticator
    - libqrencode4
  become: true

- name: Add user 'vpn-user'
  ansible.builtin.user:
    name: vpn-user
    groups: wheel
    password: "{{ 'korehavpnnopasuwa-dodesu202412' | password_hash('sha512') }}"
    create_home: true
  become: true

- name: "Remove CA directory"
  become: true
  file:
    state: absent
    path: "/home/vpn-user/openvpn-ca/"

- name: "Create CA dir"
  become: true
  command: make-cadir /home/vpn-user/openvpn-ca

- name: Customize CA variable configuration
  lineinfile:
    dest: "/home/vpn-user/openvpn-ca/vars"
    regexp: "^{{ item.property | regex_escape() }}="
    line: "{{ item.property }}={{ item.value }}"
  with_items:
    - { property: "export KEY_NAME", value: '"server"' }
    - { property: "export KEY_COUNTRY", value: '"JP"' }
    - {
        property: "export KEY_CONFIG",
        value: "/home/vpn-user/openvpn-ca/openssl-1.0.0.cnf",
      }
    - { property: "export KEY_DIR", value: "/home/vpn-user/openvpn-ca/keys" }

- name: "Build the certificate authority"
  become: true
  shell: >
    source vars;
    ./clean-all;
    yes "" | ./build-ca;
  args:
    chdir: "/home/vpn-user/openvpn-ca/"
    executable: /bin/bash

- name: "Build server certificate"
  become: true
  shell: >
    source vars;
    ./build-key-server --batch server;
  args:
    chdir: "/home/vpn-user/openvpn-ca/"
    executable: /bin/bash

- name: "Build Diffie-Hellman parameters and key generation"
  become: true
  shell: >
    source vars;
    yes "" | ./build-dh;
    openvpn --genkey --secret keys/ta.key;
  args:
    chdir: "/home/vpn-user/openvpn-ca/"
    executable: /bin/bash

- name: "Copy key and certificates to /etc/openvpn"
  become: true
  copy:
    remote_src: yes
    src: "/home/vpn-user/openvpn-ca/keys/{{ item }}"
    dest: "/etc/openvpn/"
  with_items:
    - "ca.crt"
    - "server.crt"
    - "server.key"
    - "ta.key"
    - "dh2048.pem"

- name: Adjust OpenVPN server configuration
  ansible.builtin.template:
    src: files/server.conf.j2
    dest: "/etc/openvpn/server.conf"
  become: true

- name: Configuration IP forwarding
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present

- name: Add ufw before content
  become: true
  blockinfile:
    path: /etc/ufw/before.rules
    insertbefore: BOF
    content: |
      # NAT table rules
      *nat
      :POSTROUTING ACCEPT [0:0]
      -A POSTROUTING -s {{ vpn_ip_range }} -o eth0 -j MASQUERADE
      COMMIT

- name: Customize ufw forwarding policy
  become: true
  lineinfile:
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'
    path: "/etc/default/ufw"
    regexp: '^DEFAULT_FORWARD_POLICY="DROP"'

- name: Open ufw ports for openvpn and ssh
  become: true
  shell: ufw allow openvpn && ufw allow OpenSSH

- name: Enable ufw
  become: true
  shell: ufw --force enable

- name: Start openvpn systemd service
  become: true
  systemd:
    name: openvpn@server
    state: started
    daemon_reload: yes
    enabled: yes
