- name: Update apt packages
  become: true
  apt:
    upgrade: yes

- name: Update the system
  apt:
    update_cache: yes
  become: true

- name: Install openvpn
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openvpn
    - easy-rsa
    - libpam-google-authenticator
    - libqrencode4
    - expect
  become: true

- name: "Remove CA directory"
  file:
    state: absent
    path: "/home/ansible/openvpn/"

- name: "Create CA dir"
  command: make-cadir /home/ansible/openvpn

- name: "Init the certificate authority"
  shell: ./easyrsa init-pki
  args:
    chdir: "/home/ansible/openvpn/"
    executable: /bin/bash

- name: Run ./build-ca with expect
  ansible.builtin.shell: |
    set -o pipefail
    log_file "expect_build_ca.log"
    set timeout 300
    spawn /home/ansible/openvpn/easyrsa build-ca nopass
    expect {
      -re "Common Name \\(eg: your user, host, or server name\\) \\[Easy-RSA CA\\]:" {
        send "server\n"
      } default {
        exit 1
      }
    }
    expect {
      -re "Done" {
        exit 0
      } default {
        exit 1
      }
    }
  args:
    chdir: "/home/ansible/openvpn/"
    executable: /usr/bin/expect
  failed_when: expect.rc != 0
  register: expect

- name: "Build server certificate"
  shell: ./easyrsa gen-dh
  args:
    chdir: "/home/ansible/openvpn/"
    executable: /bin/bash

- name: "Create ta.key"
  shell: openvpn --genkey secret ./pki/ta.key
  args:
    chdir: "/home/ansible/openvpn/"
    executable: /bin/bash

- name: Create server certificate with expect
  ansible.builtin.shell: |
    set -o pipefail
    log_file "expect_build_ca.log"
    set timeout 300
    spawn /home/ansible/openvpn/easyrsa build-server-full server nopass
    expect {
      -re "Confirm request details:" {
        send "yes\n"
      } default {
        exit 1
      }
    }
    expect {
      -re "Done" {
        exit 0
      } default {
        exit 1
      }
    }
  args:
    chdir: "/home/ansible/openvpn/"
    executable: /usr/bin/expect
  failed_when: expect.rc != 0
  register: expect

- name: "Copy key and certificates to /etc/openvpn"
  become: true
  copy:
    remote_src: yes
    src: "/home/ansible/openvpn/pki/{{ item }}"
    dest: "/etc/openvpn/"
  with_items:
    - "ca.crt"
    - "issued/server.crt"
    - "private/server.key"
    - "ta.key"
    - "dh.pem"

- name: Adjust OpenVPN server configuration
  ansible.builtin.template:
    src: files/server.conf.j2
    dest: "/etc/openvpn/server.conf"
  become: true

- name: Configuration IP forwarding
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present

- name: Add ufw before content
  become: true
  blockinfile:
    path: /etc/ufw/before.rules
    insertbefore: BOF
    content: |
      # NAT table rules
      *nat
      :POSTROUTING ACCEPT [0:0]
      -A POSTROUTING -s {{ vpn_ip_range }} -o eth0 -j MASQUERADE
      COMMIT

- name: Customize ufw forwarding policy
  become: true
  lineinfile:
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'
    path: "/etc/default/ufw"
    regexp: '^DEFAULT_FORWARD_POLICY="DROP"'

- name: Open ufw ports for openvpn and ssh
  become: true
  shell: ufw allow openvpn && ufw allow OpenSSH

- name: Enable ufw
  become: true
  shell: ufw --force enable

- name: Start openvpn systemd service
  become: true
  systemd:
    name: openvpn@server
    state: started
    daemon_reload: yes
    enabled: yes
