---
- name: Ensure /opt/sliver directory exists
  file:
    path: /opt/sliver
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Create proxy file in /etc/sudoers.d
  copy:
    dest: /etc/sudoers.d/proxy
    content: 'Defaults env_keep = "http_proxy https_proxy"'
    owner: root
    group: root
    mode: "0440"
  become: true

- name: Set http_proxy environment variable
  lineinfile:
    path: /etc/environment
    line: "http_proxy=http://{{proxy_server}}:{{proxy_port}}"
    create: true
  become: true

- name: Set https_proxy environment variable
  lineinfile:
    path: /etc/environment
    line: "https_proxy=http://{{proxy_server}}:{{proxy_port}}"
    create: true
  become: true

- name: Install Sliver
  shell: curl https://sliver.sh/install | sudo bash
  become: true

- name: Read file content
  slurp:
    src: /root/.sliver-client/configs/root_localhost.cfg
  register: file_content
  become: true

- name: Display file content in log
  debug:
    msg: "{{ file_content['content'] | b64decode }}"
  become: true
