substitutions:
  _ANSIBLE_PRIVATE_KEY: ""

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  pool:
    name: projects/$PROJECT_ID/locations/asia-northeast1/workerPools/private-pool

steps:
  # [START ssh-keygen]
  - id: "Create SSH Key Pair"
    name: "alpine"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        apk add --no-cache openssh
        ssh-keygen -t rsa -b 2048 -f /workspace/ansible_key -q -N ""
  # [END ssh-keygen]
  # [START Secrets create]
  - id: "Register SSH Private Key to Secret Manager"
    name: "google/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if gcloud secrets describe ansible_key &>/dev/null; then
          echo "Secret 'ansible_key' already exists. Adding a new version..."
          gcloud secrets versions add ansible_key --data-file=/workspace/ansible_key
        else
          echo "Creating new secret 'ansible_key'..."
          gcloud secrets create ansible_key --data-file=/workspace/ansible_key
        fi
  # [END Secrets create]
  - id: "tf init"
    name: "hashicorp/terraform:1.0.0"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd Terraform
        terraform init -var="public_key_path=/workspace/ansible_key.pub" -var="project=$PROJECT_ID"

  # [START tf-plan]
  - id: "tf plan"
    name: "hashicorp/terraform:1.0.0"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd Terraform
        terraform import  -var "project=$PROJECT_ID" -var "public_key_path=/workspace/ansible_key.pub" module.vpc.google_compute_network.vpc projects/$PROJECT_ID/global/networks/redteam-vpc
        terraform plan -var="public_key_path=/workspace/ansible_key.pub" -var="project=$PROJECT_ID"

  # [END tf-plan]

  # [START tf-apply]
  - id: "tf apply"
    name: "hashicorp/terraform:1.0.0"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd Terraform    
        terraform apply -auto-approve -var="public_key_path=/workspace/ansible_key.pub" -var="project=$PROJECT_ID"

  # [END tf-apply]
  # [START terraform output]
  - id: "tf output"
    name: "hashicorp/terraform:1.0.0"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd Terraform
        terraform output -json > /workspace/terraform_output.json
        cat /workspace/terraform_output.json

  # # [END terraform output]
  # [START Ansible Playbook]
  - id: "Run Ansible Playbook"
    name: "google/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud secrets versions access latest --secret=ansible_key > /workspace/ansible_key
        chmod 400 /workspace/ansible_key
        apt-get update > /dev/null 2>&1
        apt-get install -y ansible > /dev/null 2>&1
        apt-get install -y python3-google-auth > /dev/null 2>&1
        chmod 600 ~/.netrc
        ansible-galaxy collection install -f microsoft.ad --upgrade

        ssh-keygen -t rsa -b 2048 -f /workspace/tunneling_key -q -N ""
        cd Ansible
        cp -f /workspace/tunneling_key.pub roles/ssh_tunneling_dest/files/authorized_keys
        cp -f /workspace/tunneling_key roles/ssh_tunneling_src/files/id_rsa

        python3 tools/updateInventory.py  inventory/gcp.yaml  $PROJECT_ID

        ansible-inventory --graph -i inventory/gcp.yaml 
        ansible-playbook site.yml -i inventory/gcp.yaml

  - id: "tf destroy"
    name: "hashicorp/terraform:1.0.0"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        cd Terraform
        terraform destroy -auto-approve -var="public_key_path=/workspace/ansible_key.pub" -var="project=$PROJECT_ID"
