# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License..

substitutions:
  _ANSIBLE_PRIVATE_KEY: ""

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  pool:
    name: projects/$PROJECT_ID/locations/us-west1/workerPools/dev-private-pool

steps:

  # [START Ansible Playbook]
  - id: "Copy Ansible files and Run Ansible Playbook"
    name: "google/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud secrets versions access latest --secret=ansible_key > /workspace/ansible_key
        apt-get update > /dev/null 2>&1
        apt-get install -y ansible > /dev/null 2>&1
        apt-get install -y python3-google-auth > /dev/null 2>&1
        chmod 600 ~/.netrc
        ansible-galaxy collection install -f microsoft.ad --upgrade
        cd Ansible
        ansible-inventory --graph -i inventory/$BRANCH_NAME/dev_gcp.yaml
        ansible-playbook site.yml -i inventory/$BRANCH_NAME/dev_gcp.yaml

#  - id: "tf destroy"
#    name: "hashicorp/terraform:1.0.0"
#    entrypoint: "sh"
#    args:
#      - "-c"
#      - |
#        if [ -d "Terraform/environments/$BRANCH_NAME/" ]; then
#          cd Terraform/environments/$BRANCH_NAME
#          terraform destroy -auto-approve -var="public_key_path=/workspace/ansible_key.pub" -var="project=$PROJECT_ID"
##        else
#         echo "***************************** SKIPPING APPLYING *******************************"
#          echo "Branch '$BRANCH_NAME' does not represent an official environment."
#          echo "*******************************************************************************"
#        fi
