---
- name: install apache
  apt: 
    name: apache2
    state: present
- name: copy default page
  copy:
    src: index.html
    dest: /var/www/html/index.html
- name: start service
  service: 
    name: apache2
    state: started
    enabled: yes