---
- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present
  become: true

- name: Build Docker image
  docker_image:
    path: files/Dockerfile
    name: havoc_teamserver
    tag: latest
  become: yes

- name: Run Docker container
  docker_container:
    name: havoc_teamserver
    image: havoc_teamserver:latest
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "8080:8080"
      - "40056:40056"
  become: yes