---
- name: Update the system
  apt:
    update_cache: yes
  become: yes
- name: Install required packages
  apt:
    name:
      - git
      - build-essential
      - apt-utils
      - cmake
      - libfontconfig1
      - libglu1-mesa-dev
      - libgtest-dev
      - libspdlog-dev
      - libboost-all-dev
      - libncurses5-dev
      - libgdbm-dev
      - libssl-dev
      - libreadline-dev
      - libffi-dev
      - libsqlite3-dev
      - libbz2-dev
      - mesa-common-dev
      - qtbase5-dev
      - qtchooser
      - qt5-qmake
      - qtbase5-dev-tools
      - libqt5websockets5
      - libqt5websockets5-dev
      - qtdeclarative5-dev
      - golang-go
      - python3-dev
      - mingw-w64
      - nasm
      - nginx
      - ufw
      - snapd
    state: present
  become: yes

- name: Download Go 1.21.1
  ansible.builtin.get_url:
    url: https://go.dev/dl/go1.21.1.linux-amd64.tar.gz
    dest: /tmp/go1.21.1.linux-amd64.tar.gz

- name: Extract Go to /usr/local
  ansible.builtin.unarchive:
    src: /tmp/go1.21.1.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
  become: yes

- name: Change symbolic link for /usr/bin/go
  ansible.builtin.file:
    path: /usr/bin/go
    src: /usr/local/go/bin/go
    state: link
  become: yes

- name: Source the profile
  ansible.builtin.shell: source ~/.profile
  args:
    executable: /bin/bash

- name: Clone Havoc Framework repository
  git:
    repo: https://github.com/HavocFramework/Havoc.git
    dest: /opt/Havoc
    force: yes
  become: yes

- name: Install dependencies for Team Server
  command: "{{ item }}"
  args:
    chdir: /opt/Havoc/teamserver
  loop:
    - go mod download golang.org/x/sys
  #   - go mod download github.com/ugorji/go
  become: yes

- name: Build Team Server
  command: make ts-build
  args:
    chdir: /opt/Havoc
  become: yes
