---
- name: Update the system
  apt:
    update_cache: yes
  become: true
  environment:
    http_proxy: "http://{{ proxy_server }}:{{ proxy_port }}" 
    https_proxy: "http://{{ proxy_server }}:{{ proxy_port }}"

- name: Install required packages
  apt:
    name: autossh
    state: present
  environment:
    http_proxy: "http://{{ proxy_server }}:{{ proxy_port }}" 
    https_proxy: "http://{{ proxy_server }}:{{ proxy_port }}"
  become: true

- name: Create user tunneling
  ansible.builtin.user:
    name: tunneling
    state: present
    shell: /bin/bash
  become: true

- name: Create SSH directory for tunneling user
  ansible.builtin.file:
    path: /home/tunneling/.ssh
    state: directory
    owner: tunneling
    group: tunneling
    mode: "0700"
  become: true

- name: Copy SSH key
  ansible.builtin.copy:
    src: files/id_rsa
    dest: /home/tunneling/.ssh/id_rsa
    owner: tunneling
    group: tunneling
    mode: "0600"
  become: true

- name: Create ssh config file
  ansible.builtin.template:
    src: templates/ssh_config.j2
    dest: /home/tunneling/.ssh/config
    owner: tunneling
    group: tunneling
    mode: "0600"
  become: true

- name: Configure autossh for reverse port forwarding
  command: autossh -o StrictHostKeyChecking=no -o GatewayPorts=yes -M 0 -N -f tunneling
  args:
    chdir: /home/tunneling
  become: true
  become_user: tunneling
