---
- name: Set multiple lookup addresses on all visible adapters (usually physical adapters that are in the Up state), with debug logging to a file
  ansible.windows.win_dns_client:
    adapter_names: "*"
    dns_servers: "{{dns_server}}"

- name: join host to domain with automatic reboot
  microsoft.ad.membership:
    dns_domain_name: "{{domain}}"
    domain_admin_user: "Administrator@{{domain}}"
    domain_admin_password: "{{domain_password}}"
    state: domain
    reboot: true

- name: Set System-wide Proxy via Registry
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings
    name: ProxyServer
    data: "http://{{ proxy_server }}:{{ proxy_port }}"
    type: REG_SZ

- name: Enable Proxy in Registry
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings
    name: ProxyEnable
    data: 1
    type: REG_DWORD
