---
- name: Ensure Administrator password is not blank
  ansible.windows.win_user:
    name: Administrator
    password: "{{domain_password}}"
    state: present

- name: Set multiple lookup addresses on all visible adapters (usually physical adapters that are in the Up state), with debug logging to a file
  ansible.windows.win_dns_client:
    adapter_names: "*"
    dns_servers: "{{dns_server}}"

- name: Create a domain tree foo.example.com with parent bar.example.com
  microsoft.ad.domain_child:
    dns_domain_name: "{{ domain }}"
    domain_admin_user: "Administrator@{{ parent_domain }}"
    domain_admin_password: "{{domain_password}}"
    safe_mode_password: "{{domain_password}}"
    reboot: true

- name: Ensure a server is a domain controller
  microsoft.ad.domain_controller:
    dns_domain_name: "{{ domain }}"
    domain_admin_user: "Administrator@{{ domain }}"
    domain_admin_password: "{{domain_password}}"
    safe_mode_password: "{{domain_password}}"
    state: domain_controller
    reboot: true
