---
- name: Create Conditional Forwarder
  ansible.windows.win_powershell:
    script: |
      Add-DnsServerConditionalForwarderZone -Name "{{ target_domain }}" -MasterServers "{{ target_dns_ip }}" -ReplicationScope "Domain"
  ignore_errors: true

- name: Create One-Way Trust
  ansible.windows.win_powershell:
    script: |
      netdom trust {{ source_domain }} /d:{{ target_domain }} /add /realm /userD:"Administrator@{{ target_domain }}" /passwordD:{{ target_domain_password }} /userO:"Administrator@{{ source_domain }}" /passwordO:{{ source_domain_password }} /force
  ignore_errors: true
