---

###
# Install EDR to test servers
###

- hosts: gcp_group_ad_dev, gcp_group_terminal_dev,gcp_group_server_dev
  gather_facts: false
  roles:
    - roles/windows/elastic_agent
  vars:
    fleet_server: "{{ groups['gcp_group_elk'] | map('extract', hostvars, 'inventory_hostname') | first }}"
    file: windows.ps1
    domain: dev.com

- hosts: gcp_group_ad_prod
  gather_facts: false
  roles:
    - roles/windows/elastic_agent
  vars:
    fleet_server: "{{ groups['gcp_group_elk'] | map('extract', hostvars, 'inventory_hostname') | first }}"
    file: windows.ps1
    domain: prod.com

- hosts: gcp_group_proxy
  gather_facts: false
  roles:
    - roles/linux/elastic_agent
  vars:
    fleet_server: "{{ groups['gcp_group_elk'] | map('extract', hostvars, 'inventory_hostname') | first }}"
    file: proxy.sh

- hosts:
    - gcp_group_redirector
    - gcp_group_phishing
  gather_facts: false
  roles:
    - roles/linux/elastic_agent
  vars:
    fleet_server: "{{ groups['gcp_group_elk'] | map('extract', hostvars, 'inventory_hostname') | first }}"
    file: apache2.sh