---
- name: Disable host key checking on control node
  hosts: localhost
  tasks:
    - name: Ensure SSH config directory exists
      file:
        path: ~/.ssh
        state: directory
        mode: '0700'

    - name: Disable host key checking
      lineinfile:
        path: ~/.ssh/config
        line: "StrictHostKeyChecking no"
        create: yes
        mode: '0600'

- name: Install Apache
  hosts: apache
  become: yes

  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes