---
- hosts: gcp_group_redirector
  gather_facts: false
  roles:
    - apache2
- hosts: gcp_group_c2
  gather_facts: false
  roles:
    - sliver
    
- hosts: gcp_group_ad
  gather_facts: false
  roles:
    - ad

- hosts: gcp_group_proxy
  gather_facts: false
  roles:
    - squid