---
- hosts: gcp_group_redirector
  gather_facts: false
  roles:
    - apache2
- hosts: gcp_group_c2
  gather_facts: false
  roles:
    - sliver

- hosts: gcp_group_ad_dev
  gather_facts: false
  roles:
    - ad
  vars:
    domain: dev.com
    netbios_name: DEV

- hosts: gcp_group_terminal_dev
  gather_facts: false
  roles:
    - terminal
  vars:
    domain: dev.com
    dns_server_ip: "{{ hostvars[groups['gcp_group_ad_dev'][0]]['ansible_host'] }}"

- hosts: gcp_group_ad_prod
  gather_facts: false
  roles:
    - ad
  vars:
    domain: prod.com
    netbios_name: PROD

- hosts: gcp_group_proxy
  gather_facts: false
  roles:
    - squid
