---
- name: Install Sliver via curl
  shell: "curl https://sliver.sh/install | bash"
  args:
    executable: /bin/bash
  become: yes

- name: Create Sliver operator configuration
  shell: "sliver operator --name zer0cool --lhost {{ lhost_ip }} --save zer0cool.cfg"
  become: yes
  vars:
    lhost_ip: "{{ ansible_default_ipv4.address }}"

- name: Log content of zer0cool.cfg
  command: cat zer0cool.cfg
  register: cfg_content
  become: yes

- name: Print zer0cool.cfg content
  debug:
    var: cfg_content.stdout