---
- name: Install required packages
  apt:
    name:
      - git
      - build-essential
      - apt-utils
      - cmake
      - libfontconfig1
      - libglu1-mesa-dev
      - libgtest-dev
      - libspdlog-dev
      - libboost-all-dev
      - libncurses5-dev
      - libgdbm-dev
      - libssl-dev
      - libreadline-dev
      - libffi-dev
      - libsqlite3-dev
      - libbz2-dev
      - mesa-common-dev
      - qtbase5-dev
      - qtchooser
      - qt5-qmake
      - qtbase5-dev-tools
      - libqt5websockets5
      - libqt5websockets5-dev
      - qtdeclarative5-dev
      - golang-go
      - qtbase5-dev
      - libqt5websockets5-dev
      - python3-dev
      - libboost-all-dev
      - mingw-w64
      - nasm
    state: present
    update_cache: yes
  become: yes

- name: Add Debian bookworm repository
  lineinfile:
    path: /etc/apt/sources.list
    line: "deb http://ftp.de.debian.org/debian bookworm main"
    state: present
  become: yes

- name: Update apt cache after adding the repository
  apt:
    update_cache: yes
  become: yes

- name: Install additional Python packages
  apt:
    name:
      - python3-dev
      - python3.11-dev
      - libpython3.11
      - libpython3.11-dev
      - python3.11
    state: present
  become: yes


- name: Create /opt/havoc directory
  file:
    path: /opt/havoc
    state: directory
    mode: '0755'
  become: yes

- name: Clone teamserver repository (assuming you don't have it yet)
  git:
    repo: "https://github.com/HavocFramework/Havoc.git"
    dest: /opt/havoc

- name: Download Go dependencies
  command: go mod download
  args:
    chdir: /opt/havoc

- name: Run make for ts-build
  make:
    chdir: /opt/havoc
    target: ts-build

- name: Run the havoc server
  command: ./havoc server --profile ./profiles/havoc.yaotl -v --debug
  args:
    chdir: /opt/havoc
  async: 300
  poll: 0
