---
- name: Download the installation script
  ansible.windows.win_get_url:
    url: "http://{{ fleet_server }}/{{ file }}"
    dest: C:\\Users\\Ansible\\{{ file }}

- name: Execute the installation script on Windows
  win_shell: |
    powershell.exe -ExecutionPolicy Bypass -File C:\\Users\\Ansible\\{{ file }}
